== プリパラハッカソン #2 に参加しました

なんか前回やっているのを認知していて、へえ、面白そうだな… と思って参加しました。

ちなみにボクは今回ハッカソン初参加で、そのために（？）プリパラを見始めたのですが、プリパラは想像以上に尊いので見たほうが良いですね。見ましょう。

今日のyumechiくんの発言の一部を抜粋します。

[source,txt]
社会人になるとですね、心が穢れている人間たちを見るたびに、らぁらちゃんの純粋すぎる気持ちとかですね、みれぃちゃんのニンゲン臭さがですね、非常に心を打つわけで、1クールとか通してみると精神が昇華されてイッキ見とか出来ないですね・・・（体力がほしいゾ）

謎エモのオタク…。

=== イベントURL

link:https://prickathon.connpass.com/event/79677/[プリパラハッカソン #2]

=== 流れ

==== 10:00 

開始時間だったが、クリーニングを取りに行くことを忘れていたので取りに行った。（土曜日のうちに行くべきであった）

なので、遅刻。

==== 11:00

会場に到着、アイディア出ししてる人と作り始めている人が半々くらいだったかな。

特にアイディア持たずに行ってしまったので（実際ゲーム作りたいなと思ったけど、調査不足で無理そうだから諦めた）、どこかに乗っかることに。

2つ聞いて何となく作るものが浮かんできそうなLINEbotをudonさんと作ることに決めた。

==== 12:00

登録されたLINEbotを見せてもらったり、herokuの設定とかをすることにした。

herokuの設定で無限時間が溶けた。

ライブの映像が綺麗で素晴らしかった。素晴らしい。素晴らしい。（語彙力の欠如）

==== 13:00

お昼ごはんタイム。渋谷の七志。案がない時にここに頼りがちで新しい店発掘できてないけど、人数いて座りやすい店ここくらいしか知らないんだよな。。。

https://twitter.com/yumechi0525/status/977768327970938880

==== 14:00

herokuと無限に戦う。herokuアンインストールして入れ直したら上手く行った。多分前なんかやったときの認証が残っていたっぽい。

pushしたら文法エラーで落ちる大失態を犯した。すぐ直した。（普段Pythonで書いてて、このLINEbotもPythonで書いてるのに落とすのはどういうことやねん）

==== 15:00

ドキュメントを調べながらLINEbotのLocationMessageについての知見を貯めていく。これ、すごいね。

場所の情報を教えるだけではなく、ある程度の場所の情報もタイトルとして渡すことが出来る。これを上手くパースして鸚鵡返しするようにしてた。

パースは正規表現でやっていたが、動作のパターンが良くわからないのでテストで同じパターンを描いてpytest書いてUnitTestして動作確認をした。

だいたいこんな感じで動作してた。（ちなみに私の趣味で口調が完全にみれぃだった、最終的にめが姉ぇと言うの名のみれぃになってしまったので、最初からめが姉ぇに寄せていけばよかったと思う。なお、めが姉ぇの発言特徴ベクトルを人力で感じ取ることができなかった模様）

https://twitter.com/yumechi0525/status/977820297121288192

==== 16:00

API通信部分をudonさんがやっている間にリファクタリングしたり、正規表現のバグを直したりしていた。（今回の対応部分は東京だけだったが、その中でも「区】のものしか取れておらず「市」の検索も可能にした。

あとはちょいちょい動作の確認したりしてた。位置情報だけではなく、メッセージでの検索もやっていたが、「東京」を投げると検索結果が多すぎて動作がおかしくなるっぽいことを発見して、検索件数を絞る方針にするとかそういうこともしてた。

==== 17:00

リファクタリングと口調を統一する大会を開きmasterに直pushする愚かなえんじにゃーだったので、出直してきます。

その結果割りとコードがスッキリした。これ以上残りの時間でつけられそうな機能もなかったので、sample等を作ってだいたいここで終了。

（このあたりから割りと調査のためにアニメ流す用のパソコンが調子悪そうだった）

==== 18:00

前のハッカソンで作っていたというWebフロントページの出来が微妙だなあと思っていたので、marializeでサクッと見た目よく出来ないかなーと思って、いじり始める。

materialize、これまで全く触ったことがなかったのだが、ほとんど感覚としてはbootstrapだったので意外と学習に時間はかからなかった。（しかし div 地獄を発生させてしまい…）

これ以降は materialize と戯れていたら時間になってしまった。

==== 20:00

成果発表。LINEbotはつつがなくAPIの対応している範囲では完成しましたとさ。
おもったよりも良く出来てるなーと思って（私はそんなに貢献できた気がしないが）、結構達成感はあった。

Webのフロントはそれなりにきれいになったかなーって感じで、それなりの反応でした。もうちょっとしっかり直したらPR出したいな。

ほかの人が作っていたものは、壮大な野望っぽいデータ管理システム＋そのフロント（でも結構形になっててすごいなと思った）、Chrome拡張作ってたなどなど… 結構短時間にも関わらず、それなりのものが出来ているにびっくりしました。みんなすげー。これが愛の力…。


ともかく楽しい時間はあっという間に過ぎて終了。撤退しました。

==== 21:00

打ち上げをやっていていたらしいですが、トイレに篭っている間にみんな帰っていたので一人で中本に行きました。

胃袋は生きています。北極やさいの2倍が現在の限界な気がしましたね。久々に食べきれないかと思った。

https://twitter.com/yumechi0525/status/977887561350705152

=== まとめ

まず何より楽しかったです。それと結構自信につながりました。

これまでも短時間で色々作るみたいなやつはやってきたことが合ったのですが、ハッカソンでチームでやるみたいな経験はなくてですね、色々学ぶこともありましたし、Pythonに関して知っていることを共有するいい機会になりました。

あとLINEのDocumentが結構充実していて読みやすかったなあとか。（ただ、何か今日読んでいる中で無限にドキュメント不足してる漢字あるなーって思った物があったような…）

ハッカソンとしての反省は少し時間をかけてゆっくり作り込みすぎたかな、と思ったので次回はもう少しスピーディーに作りたいですね。（とはいえ、最初からしっかり作ると最終的には早くものが仕上がりやすい）

プリパラに対しての参加者の熱い愛情を感じましたし、キャラクターめっちゃかわいいし、話もしっかりしていて心動かされますし、ああ最高やな…

先日本当の意味で最終回を迎えてしまったそうですが、早いところ最後まで見てしまいたいなーと思えたので、次回のハッカソンまでには全部見てやるぞ～と思います。（今の段階だと、ソラミスマイル、ドレッシングパフェ、ファルルくらいしかネタがないので… ネタを増やす意味でも）

もっと深い話をしたいし、もっと見るべきだな、さっさと見てきます。（あと次回は素材を自分で作って、ゲームづくりにチャレンジしたいですね）


以上でした。（これ明日起きれるんかな。。。）
