== ボルタリング初経験しました

超疲れた… @drken1215 先生に連れられて link:https://js-ebisu.jimdo.com/[恵比寿にあるボルダリングシム] に行ってきました。

=== ボルダリングって何？

Wikipedia見ればわかりそう・・・ 

https://ja.wikipedia.org/wiki/%E3%83%9C%E3%83%AB%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0

シューズとチョークだけつかって壁を登ります。最近ではエンジニア界隈で流行っているという噂もあります。

実際はジムにいって壁の突起をルールにそって登っていく形になります。

突起のつかみやすさとか乗りやすさに級位とか段位がついていて、挑戦するときはそのルートに沿って同じ級位の同じマークのものを登っていきます

=== 雰囲気とか

受付のインストラクター？の方から登りやすいもの（8、7級もの）を紹介してもらい、登りました。なんかこれ、1つ級が上がる毎に一気に難しくなりません…？ 6級のものは全然歯が立ちません。逆に8級は少し簡単すぎるかなと思いました。というわけで、7級のものを中心に進める…

お店に来ている人は結構来ている人が多く、ボルダリングは休憩を多めに取りながらやるスポーツだからか結構見ている人とか話している人も多かった印象です。
行くなら何人かでいくか、既にボルダリング経験者の方と行くのが良いのかもしれません。

見ていた中だとジャンプして高いところに一気に手をかけようとチャレンジしている姿や、傾斜のきつい壁を登っていく姿とか見られて上手な人が登っているのを見ると美しいなと思います。私はつっかえつっかえなので。

ちなみにシューズはレンタル、チョークも貸し出していただけました。初回登録料も含めて2時間で2700円でしたが、下手に飲み会とか行くよりよっぽど充実してないか？ これ。と思わされるくらい楽しかったです。

=== 自分がやってたこと

7級を登っていました。6つ課題があって、そのうち4つは登れました。なんとかね。
腕を思いっきり伸ばしたり、腕だけで体重の大部分を支えたりするので、腕がパンパンだし、小さいところに載ったり、片足でバランスを取らなければいけないところがあったりと、脚もパンパンになりました。

普段から運動、しよう。あと私は子供の頃から比較的体が固いため、柔軟運動もこれから継続的にやったほうが良いのでは… と思いました。流石に硬すぎるので脚開かないし、怪我しかねないからなあ。

次は6級のものを何か挑戦してみたいので、時間を見計らってまた行ってみたいですね。（あと店内の人とコミュニケーションをとるだけの勇気がほしい）

=== 終わりに

噂になっているものを実際に経験してみるのは非常に良いことなので、これを機に行ってみたい人は行けば良いんじゃなかろうかと思います。ただ、結構疲れるのでソコだけは要注意。普段から運動している人でも瞬発力をかなり使うので、気をつけたほうが良いです。


今日はこのあとゆっくりオフロに入ってゆっくり寝ます。。。。


