== 勉強会登壇の振り返りとか

登壇してきたので振り返り。

=== 勉強会URL

link:https://supporterzcolab.com/event/478/[【サポーターズ勉強会】今から始めよう技術発信]

=== 振り返り
==== 資料作りに関して

ちょっとギリギリで頑張りすぎたかな感があるが、正直公開されたことに気がつくのに時間がかかっていて、その前の週に勉強会が公開されたことにかろうじて気がついて準備を始めた。

まあでも改めて色々書こうとすると難しかったなーと思っていて、結局本から引用してこういうことに気をつけていくといいかなと言うことを中心に書いた感じ。

僕の話は微妙だったかもしれないけど、紹介した資料はなるべく良さげな物を選んだつもりではいる。（というか、どれも正直いい本ではあったはず）

==== 発表に関して

うーん、話したいところをまとめたつもりでいたけど、思ったよりぐたぐたしてしまったかも。主にSNS・ブログで発信できない理由と、ブログを書くべしって話をしたけど、質問があればと言われてからあまり質問されなかったことを考えると、期待外してしまったかなーと思う。

正直なところ、質問があまりされないっていうのはいい発表であると思っていないので（内容を解釈して引っかかる点、深く聞きたい点が出てくるのは当然の欲求だと思うので）、まあだめだったかなという気持ちになった。

あとは技術発信の話をしているので、勉強会を聞いてこう思ったよ！っていうのをまとめてくれた人もいないし、何か響いたのかなコレ、という感じで結構思うところがあった。

とはいえ、僕自身が強いエンジニアとしてではなく、ネタをいっぱい作って書いているだけでもそれなりに反応をもらえているという話は、なんか有益な方に変わるといいな。正直、ネタありきだと思うし。

=== 次回以降に向けて

当分、長時間の発表はいいかなと思った。僕はLT大会とかで登壇してみて、ソッチのほうが1つのトピックに集中して要約して話せるので、30分とかそういうトークするのは苦手かな、という感じ。

あとはもう少し早く資料を〜とか思ったけど、結局余裕あったのって気がついたタイミングの後くらいだったので、まあ無理でしたって感じ。（正直、悩みながら4〜5時間位で作ったスライドなので、大したことしてないのだが）
凡人なので、もっと時間かけないといけないですね。

貴族会LTをまたやろうみたいな話もあるし、そっちをちゃんとやるほうがまだいいのかなという気がしてきた。あとはちゃんと話すネタはいいとして、練り込まないとな、とか。


今回の発表を反面教師にして、次の発表を誰か頑張ってくれるといいかなと思います。終わり。







