== 学生LTに参加した方がいい理由

学生LTのAdventカレンダー見たら埋まっていなかったので、埋めます。
12日目のカレンダーになります。（自分のAdventカレンダーも兼任しています）

タイトルの通りですが、もう少し細かく描いていこうと思いました。

以前描いた記事はこちらになります。
link:http://yumechi0525.hatenablog.com/entry/2017/09/02/160439[学生LTを見学してきました - 夢の水面下]

=== お断り

*私は学生ではありませんし、学生LTに参加したことも9月の一度きりなので、現状とはかけ離れている可能性もありますし、視点としてもバイアスがかかっていることを前提としてください。*

=== 私が参加した回について

かなり前だった… 9月2日

link:https://student-lt.connpass.com/event/64271/[第3回 学生エンジニア限定LT大会！！！]

現在は第7回までが開催されているようです。学生以外の人でも少しだけ枠があるので、もし学生の方と触れ合いたい方は行くと良いんじゃないでしょうか。footnote:[ただし私の経験上、ビジネスオーラバリバリの人間が入っていくとLT大会や勉強会が壊れることが知られているので大人げないことは止めようね]

=== 時間が立ってからあの日感じたこと

Nafmo Combとかにも参加していて、学生コミュニティとは色々なところで縁があるのですが、改めて良かったなということを書いてみようと思います。

==== 年齢やバックグラウンドが異なる学生同士の交流

学生LTの参加者は大学生がメインであることが多いため、そう感じていないことも置いのかもしれませんが、趣味または仕事でプログラムを書いている学生と出会うことが出来る価値は凄まじいと思います。

正直なことを書くと、私の学生時代は趣味でプログラム書いている人も稀でしたし、こういうイベント自体もほぼありませんでした。（あっても学生限定でないことが多く、興味のないおっさんの話を聞かされるのが嫌で、避けていました）

同年代のやる気のある人に出会えるだけでも、十分価値があるように思います。

==== 発表ジャンルがバラけている

これ良いことでもあるし、悪いことでもありますが、LTという性質上、深く掘り下げた話をするのは難しいため、私は良いこととして捉えています。

正直、人生には時間的な上限が存在しているため、何でもかんでもやるというのは現実的ではありません（私は比較的何でもかんでもやっているように見せているけど）

学生LTではプログラミング言語から、ハードウェア、セキュリティ、開発手法やツールまで、成果物としてもスマートフォンであったり、コンソールアプリであったり、WEBサイトであったりと多種多様で、どの話を聞いていても面白く感じましたし、知見が広がりました。

（あと正直発表のレベルは入門レベルもあれば、かなり応用レベルの話もあってすげえなと思います。ほんま学生なのか？？？）


LTで登壇することも大切ですが、聞く方一辺倒でも広範囲に知ることが出来ました。飛び入りLTもあってすごい。

==== 毎回豪華な会場！！

これは学生LTじゃないと味わえないと思うのですが、毎回会場が非常に豪華です。過去の発表場所を見ればわかります…。

私が行ったときは、あのマイクロソフト様のオフィスでした。次回はfreee様らしいですね。

普通に生活しているとなかなか有名な会社の中に入って、雰囲気を経験するということはないと思います。大体イベントスペースだけしか見られないとは思うのですが、入口の雰囲気とか各社違うものがあると思うので、その辺を楽しみにしてみるのも良いんじゃないかなと思います。

というか、普通に会場良すぎてどういうコネクションがあるのか・・・www

==== 懇親会もある

これ私は参加したことがないので、一般論だけ話しますが、懇親会がちゃんと用意されているのは良いなと思います。

発表者と交流する場を通して、様々なことを学ぶチャンスでもありますし、思いがけない情報をゲットしたり、相手と交流する中で様々なことを気づくチャンスでもあります。

ある人は勉強会、LT大会は懇親会こそが本番、という名言（迷言？）を残すほどなので、それくらい人と話すことは重要ですよ！

ぜひコアなネタで盛り上がっていきましょう！！


=== というわけでね

参加していくと良いんじゃないんでしょうか、損することはないと思われます。

学生以外の人にも少しだけ枠がありますし、逆に学生であればLTを経験する絶好のチャンスなわけで、どんどん話していけばいいと思います。（登壇する機会は自分で探さないと無いので… そして早めに経験しておくことで、将来大きなところで発表するいい気機会になるかもしれません）


もし運営に興味があるとかであればスタッフも募集しているみたいですし、そういう形で関わってみるのも面白いのではないでしょうか。
優しくてエンジニアリングに詳しい人とゆる～く繋がれるチャンスなので、ぜひ
。


以上です。第7回はいけたら行くかな程度なので、もし合う機会があればよろしくお願いします。



