== はじめての開発合宿に行ってきた話

これもう9月の頭ですごい前の話なんですが、開発合宿的なものに行ってきました。

メンバーは貴族会LTとかを通して知り合った人とかです。

（LTの記事はこの辺にリンクを貼る）

=== 日程とか

9/8, 9の2日間で行ってきました。場所は都内からちょっと離れた場所がいいね、って話をしていたのですが、合意をとった結果鎌倉に決まりました。

鎌倉、行ってみるとわかりますがそんなに離れておらず、行きやすいのでいいですね。都内からは1時間〜1時間半くらいでした。

ちなみに泊まった場所はここです。Wifi完備、広いお風呂、由比ヶ浜にも近いと、いいところばかりでした。

=== 準備編

まず日程調整が大変でした。結構忙しい人たちの集まりなので、日程は1ヶ月前にこのへんで！みたいなのを決めて、後は場所の候補を出しました。

候補地として上がったのは

* 静岡（熱海とか、箱根）
* 鎌倉
* 千葉の東側

でしたが、移動の利便性等を考え、鎌倉になりました。（ついでに聖地巡礼ができるのも美味しかったです）

で、ホテルの予約ですが、条件を満たすところがあまりないかつ、この時点で3週間前ということがあり、探すのは難航していて、ぼくもこの時期結構忙しくて見ている暇がありませんでした。メンバーの1人がいい感じに場所の候補を持ってきてくれたので、上にあげたホテルに決定しました。


その他、準備することはちょいちょいありましたが、基本的にはホテル代の確認と、チェックイン・チェックアウト時間の意識だけでなんとかなりました。

唯一失敗したかな？と思ったのは、電源の数が足りず、延長ケーブルを急遽ぼくが買いに行ったくらいでしょうか。

泊まった場所が素晴らしかったので、殆どのものは完備されており、思っていた以上にめっちゃ楽でよかった… という気持ちでいっぱいです。

=== 当日の成果物

PyCon JPのLTで話すスライドのプロトタイプを書きました。

リンクこれ

この件もまとめておく必要があるのですが… また今度。

あとはnginxをちょっと触ってみたり。

=== 当日1日目の動き

* 何があるかわからないので服＋洗面具とか色々準備してた
* 電源タップ頼まれたので持っていくことになり、結局出たのが16時頃、到着は17時半か、18時頃
** ついた時間あまり正確に覚えていない
* ついてとりあえず挨拶、荷物をバラバラにする
* 19時くらいまでスライドの全容を考える
* 19時半くらいになり、ご飯を考え始める
** しらす丼を食べに行く
** 後から調べてわかったが、あまりいい店じゃなかった
** （どこも観光地値段＋20時にはしまっている場所が多いので、リサーチ不足だったかも）
* ホテルに戻って開発再開、このとき20時半〜21時くらい
* 順繰りでお風呂に入る必要があったので、22時くらいまで作業
* お風呂タイム
** 大きいお風呂で、どうやら最後だったのでゆっくり入る
** めっちゃ気持ちよかった
** お風呂は広くのんびりできるところとか、温泉が良いなあとしみじみ思う
* 1時位まで引き続き作業、だいたいスライドのプロトタイプができる
* 気持ちを切り替えて色々作っていくと捗るなあと思った

=== 当日2日目

* 早く起きたので早朝から活動
* 少し散歩に行く
* 思ったより海が近くてびっくりした
* 朝食が美味しかった。朝食が美味しいところに泊まるべし。
* チェックアウトまで荷物をまとめつつ、仮面ライダーを見て開発
** この頃nginx入れてhello, worldだけした
** nginxこれ以降触れていないので、wsgiと合わせて小さいアプリ作っていきたいな
* 宿を出る。集合写真を撮る。
* 由比ヶ浜の方にちょっと行く。見晴らしが良かった

写真ここ

* 鎌倉駅に戻ってご飯を食べ、各自行動開始
* 八幡宮に行く
** いざ鎌倉シールを手に入れた
* 極楽寺の方に行き、風景を楽しむ
** 実はエルフェンリートの関連地だったりする

写真ここ

* 長谷に移動し、大仏を見に行く
** この日はまつりとかぶっていて、神輿が歩いていた
** 神輿が歩いているので想定外に混んでいて辛かった
* 途中でお茶をしてお寺へ。大仏を撮る。

写真ここ

* きれいに空が晴れていたので、圧巻だった。てか改めてでけえよと思った。
* 鎌倉の大仏の中には入れるので、入ってみる
** めちゃくちゃ蒸し暑かった
** 中には小銭がいっぱいおいてあった。何なんだろう。
** 説明とか見てると結構補修されたりしてるんだな… と思った
** 鋳造の仕方とか結構面白い
* 鎌倉駅に戻る
* そのまま東京へ帰る
** よるごはんはラーメンでした
** 実は、1日目の夜も、2日目の昼も微妙で外してたので、一番マトモなご飯を食べたような気がします
* 帰宅

=== 感想とか

開発がってやりつつも、自然に囲まれた場所っていうのは新鮮で良かったです。鎌倉、めっちゃいいところやん住みたい！と思いましたが、若干都内で仕事するには遠いかもなとは思いました。（横浜勤務だったら十分ありなのかもしれないが）

開発合宿でメインである、開発の方でも実績が出せましたし、帰り際には色々なところを観光できたのも大きかったです。鎌倉の魅力に触れることができる良い日程でした。

普段都会で息苦しくなっているところで、ガス抜きできるいい機会だったかなーと思います。都会で疲弊している人はぜひ行ってみましょう。自然というものは心をきれいにしてくれますよ！

あと欲を言えば江ノ島にも行きたかったなーと思うので、出かける機会を見計らって再挑戦したいです。次は江ノ電を鎌倉の逆の方から乗ってみようかな？（駅メモを埋め忘れたので、それもついでにやりたい…）

いっぱい思い出に残る素敵な開発になりました。やろうと言ってくれた人たち、宿を予約してくれたメンバー、最高だったね。

またよかったら行きたいなーと思っているので、開発合宿やるよ！ぜひ着てね！って人がいたら乗っかりたいです。（自分で企画してもいいけどね）

終わり
 
